### ISSUE TITLE
Method to extract all embeds

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/subsume#1]
Could maybe be useful to have a static `Subsume.parseAll(text, [ids])` method to extract all embeds in some text. Optionally supply an iterable of `id`'s to extract.

I don't really need this right now, but pull request welcome :)

**Comment by Areadrill** [comment]
Hi there,

I have a solution in the works for this, but I'd like to clear some questions:

- When extracting the data for each embed, are the other embeds supposed remain as part of the "rest" property?

- When one string has two embeds with the same id, is the parser supposed to consider everything between the prefix of the first embed and the suffix of the last one as "data"?. I ask because that's the behaviour currently with the parse method.

**Comment by sindresorhus** [comment]
> When extracting the data for each embed, are the other embeds supposed remain as part of the "rest" property?

Yes, it should only touch the given `ids` if specified. The rest are left unparsed in the `rest` property.

> When one string has two embeds with the same id, is the parser supposed to consider everything between the prefix of the first embed and the suffix of the last one as "data"?. I ask because that's the behaviour currently with the parse method.

If it's nested inside another the other embed, then yes. If there are two embeds with the same ID and not nested, I think we should throw, as each embed should have a unique ID.

---

I didn't mention this in the original issue, but what do you think about making the return value an object with `data` and `rest` properties, where `data` is a `Map` with the `id` as key and the embed data as value?

**Comment by Areadrill** [comment]
>If it's nested inside another the other embed, then yes. If there are two embeds with the same ID and not nested, I think we should throw, as each embed should have a unique ID.

I see. I can add that to my solution. Should we open a new issue about the behaviour of the normal parse? It doesn't follow what you just specified, I think.

> I didn't mention this in the original issue, but what do you think about making the return value an object with data and rest properties, where data is a Map with the id as key and the embed data as value?

What I have right now is an array like this:

```
[ '7febcd0b3806fbc48c01d7cea4ed1219': { data: '🦄',
    rest: 'some random @@[7febcd0b3806fbc48c01d7cea4ed1218]@@🦄##[7febcd0b3806fbc48c01d7cea4ed1218]## text @@[7febcd0b3806fbc48c01d7cea4ed1217]@@🦄##[7febcd0b3806fbc48c01d7cea4ed1217]##' },
  '7febcd0b3806fbc48c01d7cea4ed1218': { data: '🦄',
    rest: 'some@@[7febcd0b3806fbc48c01d7cea4ed1219]@@🦄##[7febcd0b3806fbc48c01d7cea4ed1219]## random  text @@[7febcd0b3806fbc48c01d7cea4ed1217]@@🦄##[7febcd0b3806fbc48c01d7cea4ed1217]##' },
  '7febcd0b3806fbc48c01d7cea4ed1217': { data: '🦄',
    rest: 'some@@[7febcd0b3806fbc48c01d7cea4ed1219]@@🦄##[7febcd0b3806fbc48c01d7cea4ed1219]## random @@[7febcd0b3806fbc48c01d7cea4ed1218]@@🦄##[7febcd0b3806fbc48c01d7cea4ed1218]## text ' } ]
```

From the follwing output:

```
some@@[7febcd0b3806fbc48c01d7cea4ed1219]@@🦄##[7febcd0b3806fbc48c01d7cea4ed1219]## random @@[7febcd0b3806fbc48c01d7cea4ed1218]@@🦄##[7febcd0b3806fbc48c01d7cea4ed1218]## text @@[7febcd0b3806fbc48c01d7cea4ed1217]@@🦄##[7febcd0b3806fbc48c01d7cea4ed1217]##
```

I can do it as a map, if you think it's better. In my opinion, both solutions are okay. Would the returned object follow the same logic for the rest property as for the data property (map with the id as key and the string as value)?

**Comment by sindresorhus** [comment]
> Should we open a new issue about the behaviour of the normal parse? It doesn't follow what you just specified, I think.

👍 

> I can do it as a map, if you think it's better. In my opinion, both solutions are okay.

Yeah, I think a `Map` would be best, as the common use-case is to get out the data by ID, and with a `Map`, you can then just do `.parseAll(…).data.get(id)`.

> Would the returned object follow the same logic for the rest property as for the data property (map with the id as key and the string as value)?

The `rest` property is just a string.

**Comment by Areadrill** [comment]
>The rest property is just a string.

Yeah, but it's a string per ID, right? Or am I misunderstanding?

What I was thinking was:

```
{data: Map(id => embed data), rest: Map(id => rest}
```

**Comment by sindresorhus** [comment]
No, `.rest` is just the input string with all (or the specified IDs) the embeds removed.

**Comment by Areadrill** [comment]
Ah, I see. Will work on that as soon as I'm able.

**Comment by Areadrill** [comment]
One last question:

I now have the method returning the object with a Map and remaining string. How should the parseAll method handle nested embeds? Does it parse them as well?

**Comment by sindresorhus** [comment]
It should not parse nested embeds.
